#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.175.182.240:80 check
    server web-02 44.210.130.80:80 check
EOF'

# Enable HAProxy to start via init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

echo "HAProxy installation and configuration completed successfully!"

