#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 8?
# configures nginx to run and listen to port 80

rm /etc/nginx/Sites-enabled/default
cd /etc/nginx/sites-enabled/
ln -s ../Sites-available/default
Service nginx restart
Curl 0:80
