#!/usr/bin/env bash
# transfer file to server

# Check if all 4 parameters are provided
if [ $# -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Extract parameters
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Transfer the file using scp
scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip:~/"

# Exit with the scp return code
exit $?
